name: Copy Fork on Sync Comment

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Print head and base SHA
        run: |
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"

          echo "Example secret: ${{ secrets.EXAMPLE_SECRET }}"